const vehiculos = [
    {id: 1, nombre: "Chevrolet Spark", disponibilidad: 3, img: "", gama: "Baja", capacidad: "4", motor: "1.0L", precioXDia: 150000},
    {id: 2, nombre: "Chevrolet Spark gt", disponibilidad: 3, img: "", gama: "Baja", capacidad: "4", motor: "1.2L", precioXDia: 150000},
    {id: 3, nombre: "Chevrolet Sail", disponibilidad: 3, img: "", gama: "Baja", capacidad: "4", motor: "1.4L", precioXDia: 160000},
    {id: 4, nombre: "Renault Logan", disponibilidad: 3, img: "", gama: "Baja", capacidad: "4", motor: "1.6L", precioXDia: 160000},
    {id: 5, nombre: "Renault Sandero", disponibilidad: 3, img: "", gama: "Baja", capacidad: "4", motor: "1.6L", precioXDia: 155000},
    {id: 6, nombre: "Renault Kwid", disponibilidad: 3, img: "", gama: "Baja", capacidad: "4", motor: "1.0L", precioXDia: 140000},
    {id: 7, nombre: "Renault Duster", disponibilidad: 3, img: "", gama: "Baja", capacidad: "4", motor: "1.3L turbo", precioXDia: 180000},
    {id: 8, nombre: "Chevrolet Captiva", disponibilidad: 3, img: "", gama: "Baja", capacidad: "4", motor: "1.5L turbo", precioXDia: 190000},
    {id: 9, nombre: "Volkswagen Polo", disponibilidad: 3, img: "", gama: "Baja", capacidad: "4", motor: "1.2L", precioXDia: 160000},
    {id: 10, nombre: "Suzuki Swift", disponibilidad: 3, img: "", gama: "Baja", capacidad: "4", motor: "1.2L", precioXDia: 160000},
    {id: 11, nombre: "Mazda 2", disponibilidad: 3, img: "", gama: "Media", capacidad: "4", motor: "1.5L", precioXDia: 180000},
    {id: 12, nombre: "Mazda 3", disponibilidad: 3, img: "", gama: "Media", capacidad: "4", motor: "2.5L", precioXDia: 200000},
    {id: 13, nombre: "Mazda CX-30", disponibilidad: 3, img: "", gama: "Media", capacidad: "4", motor: "2.0L", precioXDia: 200000},
    {id: 14, nombre: "Mazda CX-5", disponibilidad: 3, img: "", gama: "Media", capacidad: "4", motor: "2.5L", precioXDia: 220000},
    {id: 15, nombre: "Ford Scape", disponibilidad: 3, img: "", gama: "Media", capacidad: "4", motor: "2.0L", precioXDia: 220000},
    {id: 16, nombre: "Ford Bronco", disponibilidad: 3, img: "", gama: "Media", capacidad: "4", motor: "2.7L biturbo", precioXDia: 250000},
    {id: 17, nombre: "Ford Explorer", disponibilidad: 3, img: "", gama: "Media", capacidad: "4", motor: "3.0L", precioXDia: 250000},
    {id: 18, nombre: "Ford Ranger", disponibilidad: 3, img: "", gama: "Media", capacidad: "4", motor: "3.0L", precioXDia: 250000},
    {id: 19, nombre: "Toyota Corolla", disponibilidad: 3, img: "", gama: "Media", capacidad: "4", motor: "2.0L", precioXDia: 220000},
    {id: 20, nombre: "Volvo Xc60", disponibilidad: 3, img: "", gama: "Media", capacidad: "4", motor: "2.0L", precioXDia: 220000},
    {id: 21, nombre: "Toyota 4runner", disponibilidad: 3, img: "", gama: "Media-Alta", capacidad: "4", motor: "4.0L", precioXDia: 450000},
    {id: 22, nombre: "Toyota Prado Tx-l", disponibilidad: 3, img: "", gama: "Media-Alta", capacidad: "4", motor: "2.4L turbo", precioXDia: 450000},
    {id: 23, nombre: "Ford Explorer ST", disponibilidad: 3, img: "", gama: "Media-Alta", capacidad: "4", motor: "2.3L turbo", precioXDia: 500000},
    {id: 24, nombre: "Chevrolet Tahoe", disponibilidad: 3, img: "", gama: "Media-Alta", capacidad: "4", motor: "5.3L", precioXDia: 650000},
    {id: 25, nombre: "Ford Raptor", disponibilidad: 3, img: "", gama: "Media-Alta", capacidad: "4", motor: "3.5L biturbo", precioXDia: 600000},
    {id: 26, nombre: "Chevrolet Silverado", disponibilidad: 3, img: "", gama: "Media-Alta", capacidad: "4", motor: "6.2L", precioXDia: 500000},
    {id: 27, nombre: "Audi Q5", disponibilidad: 2, img: "", gama: "Media-Alta", capacidad: "4", motor: "2.0L", precioXDia: 600000},
    {id: 28, nombre: "Audi Q2", disponibilidad: 3, img: "", gama: "Media-Alta", capacidad: "4", motor: "1.6L", precioXDia: 450000},
    {id: 29, nombre: "Audi Q3", disponibilidad: 3, img: "", gama: "Media-Alta", capacidad: "4", motor: "2.5L", precioXDia: 500000},
    {id: 30, nombre: "Audi Q7", disponibilidad: 2, img: "", gama: "Media-Alta", capacidad: "4", motor: "4.0L", precioXDia: 800000},
    {id: 31, nombre: "Mercedes Benz GLC 300", disponibilidad: 3, img: "", gama: "Alta", capacidad: "4", motor: "2.0L turbo", precioXDia: 900000},
    {id: 32, nombre: "Mercedes Benz G63", disponibilidad: 2, img: "", gama: "Alta", capacidad: "4", motor: "4.0L biturbo", precioXDia: 1600000},
    {id: 33, nombre: "Mercedes Benz A45", disponibilidad: 2, img: "", gama: "Alta", capacidad: "4", motor: "2.0L turbo", precioXDia: 1000000},
    {id: 34, nombre: "Audi Q8", disponibilidad: 2, img: "", gama: "Alta", capacidad: "4", motor: "3.0L turbo", precioXDia: 1500000},
    {id: 35, nombre: "Porsche Cayenne", disponibilidad: 2, img: "", gama: "Alta", capacidad: "4", motor: "4.0L", precioXDia: 1500000},
    {id: 36, nombre: "Porsche Turbo S", disponibilidad: 1, img: "", gama: "Alta", capacidad: "2", motor: "3.8L biturbo", precioXDia: 2000000},
    {id: 37, nombre: "Porsche GT3", disponibilidad: 1, img: "", gama: "Alta", capacidad: "2", motor: "4.0L", precioXDia: 2000000},
    {id: 38, nombre: "Audi R8", disponibilidad: 1, img: "", gama: "Alta", capacidad: "2", motor: "4.0L", precioXDia: 2000000},
    {id: 39, nombre: "Ferrari F8", disponibilidad: 1, img: "", gama: "Alta", capacidad: "2", motor: "3.9L twinturbo", precioXDia: 2000000},
    {id: 40, nombre: "Mercedes Benz AMG GTR", disponibilidad: 1, img: "", gama: "Alta", capacidad: "2", motor: "4.0L biturbo", precioXDia: 2000000},
]